services:
  backend:
    build:
      context: backend/secureguard-deploy
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend/secureguard-deploy/data:/app/data
    environment:
      - DATA_DIR=/app/data
  frontend:
    build:
      context: frontend_src
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
