"""
org_core.repository — 存储接口(仓储模式)。

业务/鉴权代码只依赖这些接口,不知道底下是 SQLite 还是 Postgres。
→ 小公司用 SqliteRepos(单机),大公司换 PostgresRepos(集群),业务零改动。
这是"一套代码、大小公司通吃"的关键纪律。
"""
from __future__ import annotations

from typing import Optional, Protocol

from .models import AdminScope, AuditEntry, Grant, OrgNode, Role, Tenant, User


class Repos(Protocol):
    # --- tenant ---
    def add_tenant(self, t: Tenant) -> None: ...
    def get_tenant(self, tenant_id: str) -> Optional[Tenant]: ...

    # --- org tree ---
    def add_node(self, n: OrgNode) -> None: ...
    def get_node(self, tenant_id: str, node_id: str) -> Optional[OrgNode]: ...
    def children(self, tenant_id: str, node_id: Optional[str]) -> list[OrgNode]: ...
    def update_node(self, n: OrgNode) -> None: ...           # 改名/改父(合并/拆分)

    # --- users ---
    def add_user(self, u: User) -> None: ...
    def get_user(self, tenant_id: str, user_id: str) -> Optional[User]: ...
    def set_user_status(self, tenant_id: str, user_id: str, status: str) -> None: ...

    # --- roles(岗位)---
    def add_role(self, r: Role) -> None: ...
    def get_role(self, tenant_id: str, role_id: str) -> Optional[Role]: ...

    # --- grants(子账号)---
    def add_grant(self, g: Grant) -> None: ...
    def get_grant(self, tenant_id: str, grant_id: str) -> Optional[Grant]: ...
    def grants_of_user(self, tenant_id: str, user_id: str) -> list[Grant]: ...
    def set_grant_active(self, tenant_id: str, grant_id: str, active: bool) -> None: ...

    # --- admin scopes ---
    def add_admin_scope(self, s: AdminScope) -> None: ...
    def admin_scopes_of(self, tenant_id: str, user_id: str) -> list[AdminScope]: ...

    # --- audit ---
    def append_audit(self, e: AuditEntry) -> None: ...
    def last_audit_hash(self, tenant_id: str) -> str: ...
    def list_audit(self, tenant_id: str, limit: int = 100) -> list[AuditEntry]: ...
